### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by yayahgh** [Jungyhuk/plotcoder#1]
Hi, Dear Author @Jungyhuk ，i try to replicate the experiments of poltcoder(**python run.py --nl --use_comments --code_context --nl_code_linking --copy_mechanism --hierarchy --target_code_transform**)，but it throw a **TypeError error**(**TypeError: argument of type 'Nonetype' is not iterable**) in line 313 of data_untils.py(if 'func' not in ast_tree:). I found when parse the cur_code(**['for', 'curve', 'in', 'curvePoints', ':', 'ax', '.', 'plot', '(', 'curve', '[', ':', ',', '0', ']', ',', 'curve', '[', ':', ',', '1', ']', ',', 'curve', '[', ':', ',', '2', ']', ')', '\n']**), ast_tree['body'][0]['value'] is a **NoneType**.
How should i go about resolving this issue?

**Comment by Jungyhuk** [comment]
Thanks for pointing out! I didn't encounter this issue, probably due to the different Python versions we use. I made a small code change to bypass the issue.

**Comment by hongnhungocvn99** [comment]
Hello friends, I found this article quite interesting and now I am running a test of it. However, I am having a problem, I don't know if you can help me. The problem was I cut train.jsol to get 3000 lines then I ran Data preprocessing. And To run the hierarchical model as instructed: "python run.py --nl --use_comments --code_context --nl_code_linking --copy_mechanism --hierarchy --target_code_transform". But after running it, I didn't find any result files. Can you tell me where the problem lies?
